// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type UserInput struct {
	Username  string `json:"username"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Email     string `json:"email"`
	Password  string `json:"password"`
}
